# permissions for end users to view migrators.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: migrator-viewer-role
rules:
- apiGroups:
  - migrations.coderanger.net
  resources:
  - migrators
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - migrations.coderanger.net
  resources:
  - migrators/status
  verbs:
  - get
